// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_book.proto

package com.scratch.address_book;

public final class AddressBookEntryProto {
  private AddressBookEntryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressBookEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:address_book.AddressBookEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .person.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>optional .person.Person person = 1;</code>
     * @return The person.
     */
    com.scratch.person.PersonProto.Person getPerson();
    /**
     * <code>optional .person.Person person = 1;</code>
     */
    com.scratch.person.PersonProto.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>optional .contact.Contact contact = 2;</code>
     * @return Whether the contact field is set.
     */
    boolean hasContact();
    /**
     * <code>optional .contact.Contact contact = 2;</code>
     * @return The contact.
     */
    com.scratch.contact.ContactProto.Contact getContact();
    /**
     * <code>optional .contact.Contact contact = 2;</code>
     */
    com.scratch.contact.ContactProto.ContactOrBuilder getContactOrBuilder();
  }
  /**
   * Protobuf type {@code address_book.AddressBookEntry}
   */
  public static final class AddressBookEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:address_book.AddressBookEntry)
      AddressBookEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddressBookEntry.newBuilder() to construct.
    private AddressBookEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressBookEntry() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddressBookEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBookEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.scratch.person.PersonProto.Person.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(com.scratch.person.PersonProto.Person.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.scratch.contact.ContactProto.Contact.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = contact_.toBuilder();
              }
              contact_ = input.readMessage(com.scratch.contact.ContactProto.Contact.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contact_);
                contact_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scratch.address_book.AddressBookEntryProto.internal_static_address_book_AddressBookEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scratch.address_book.AddressBookEntryProto.internal_static_address_book_AddressBookEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.class, com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.Builder.class);
    }

    private int bitField0_;
    public static final int PERSON_FIELD_NUMBER = 1;
    private com.scratch.person.PersonProto.Person person_;
    /**
     * <code>optional .person.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .person.Person person = 1;</code>
     * @return The person.
     */
    @java.lang.Override
    public com.scratch.person.PersonProto.Person getPerson() {
      return person_ == null ? com.scratch.person.PersonProto.Person.getDefaultInstance() : person_;
    }
    /**
     * <code>optional .person.Person person = 1;</code>
     */
    @java.lang.Override
    public com.scratch.person.PersonProto.PersonOrBuilder getPersonOrBuilder() {
      return person_ == null ? com.scratch.person.PersonProto.Person.getDefaultInstance() : person_;
    }

    public static final int CONTACT_FIELD_NUMBER = 2;
    private com.scratch.contact.ContactProto.Contact contact_;
    /**
     * <code>optional .contact.Contact contact = 2;</code>
     * @return Whether the contact field is set.
     */
    @java.lang.Override
    public boolean hasContact() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .contact.Contact contact = 2;</code>
     * @return The contact.
     */
    @java.lang.Override
    public com.scratch.contact.ContactProto.Contact getContact() {
      return contact_ == null ? com.scratch.contact.ContactProto.Contact.getDefaultInstance() : contact_;
    }
    /**
     * <code>optional .contact.Contact contact = 2;</code>
     */
    @java.lang.Override
    public com.scratch.contact.ContactProto.ContactOrBuilder getContactOrBuilder() {
      return contact_ == null ? com.scratch.contact.ContactProto.Contact.getDefaultInstance() : contact_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPerson());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getContact());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPerson());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContact());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scratch.address_book.AddressBookEntryProto.AddressBookEntry)) {
        return super.equals(obj);
      }
      com.scratch.address_book.AddressBookEntryProto.AddressBookEntry other = (com.scratch.address_book.AddressBookEntryProto.AddressBookEntry) obj;

      if (hasPerson() != other.hasPerson()) return false;
      if (hasPerson()) {
        if (!getPerson()
            .equals(other.getPerson())) return false;
      }
      if (hasContact() != other.hasContact()) return false;
      if (hasContact()) {
        if (!getContact()
            .equals(other.getContact())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPerson()) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
      }
      if (hasContact()) {
        hash = (37 * hash) + CONTACT_FIELD_NUMBER;
        hash = (53 * hash) + getContact().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scratch.address_book.AddressBookEntryProto.AddressBookEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code address_book.AddressBookEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:address_book.AddressBookEntry)
        com.scratch.address_book.AddressBookEntryProto.AddressBookEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scratch.address_book.AddressBookEntryProto.internal_static_address_book_AddressBookEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scratch.address_book.AddressBookEntryProto.internal_static_address_book_AddressBookEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.class, com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.Builder.class);
      }

      // Construct using com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
          getContactFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = null;
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contactBuilder_ == null) {
          contact_ = null;
        } else {
          contactBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scratch.address_book.AddressBookEntryProto.internal_static_address_book_AddressBookEntry_descriptor;
      }

      @java.lang.Override
      public com.scratch.address_book.AddressBookEntryProto.AddressBookEntry getDefaultInstanceForType() {
        return com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.scratch.address_book.AddressBookEntryProto.AddressBookEntry build() {
        com.scratch.address_book.AddressBookEntryProto.AddressBookEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scratch.address_book.AddressBookEntryProto.AddressBookEntry buildPartial() {
        com.scratch.address_book.AddressBookEntryProto.AddressBookEntry result = new com.scratch.address_book.AddressBookEntryProto.AddressBookEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (personBuilder_ == null) {
            result.person_ = person_;
          } else {
            result.person_ = personBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (contactBuilder_ == null) {
            result.contact_ = contact_;
          } else {
            result.contact_ = contactBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scratch.address_book.AddressBookEntryProto.AddressBookEntry) {
          return mergeFrom((com.scratch.address_book.AddressBookEntryProto.AddressBookEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scratch.address_book.AddressBookEntryProto.AddressBookEntry other) {
        if (other == com.scratch.address_book.AddressBookEntryProto.AddressBookEntry.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        if (other.hasContact()) {
          mergeContact(other.getContact());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scratch.address_book.AddressBookEntryProto.AddressBookEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scratch.address_book.AddressBookEntryProto.AddressBookEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.scratch.person.PersonProto.Person person_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.person.PersonProto.Person, com.scratch.person.PersonProto.Person.Builder, com.scratch.person.PersonProto.PersonOrBuilder> personBuilder_;
      /**
       * <code>optional .person.Person person = 1;</code>
       * @return Whether the person field is set.
       */
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       * @return The person.
       */
      public com.scratch.person.PersonProto.Person getPerson() {
        if (personBuilder_ == null) {
          return person_ == null ? com.scratch.person.PersonProto.Person.getDefaultInstance() : person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public Builder setPerson(com.scratch.person.PersonProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public Builder setPerson(
          com.scratch.person.PersonProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public Builder mergePerson(com.scratch.person.PersonProto.Person value) {
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              person_ != null &&
              person_ != com.scratch.person.PersonProto.Person.getDefaultInstance()) {
            person_ =
              com.scratch.person.PersonProto.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = null;
          onChanged();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public com.scratch.person.PersonProto.Person.Builder getPersonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      public com.scratch.person.PersonProto.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_ == null ?
              com.scratch.person.PersonProto.Person.getDefaultInstance() : person_;
        }
      }
      /**
       * <code>optional .person.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.person.PersonProto.Person, com.scratch.person.PersonProto.Person.Builder, com.scratch.person.PersonProto.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.scratch.person.PersonProto.Person, com.scratch.person.PersonProto.Person.Builder, com.scratch.person.PersonProto.PersonOrBuilder>(
                  getPerson(),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      private com.scratch.contact.ContactProto.Contact contact_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.contact.ContactProto.Contact, com.scratch.contact.ContactProto.Contact.Builder, com.scratch.contact.ContactProto.ContactOrBuilder> contactBuilder_;
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       * @return Whether the contact field is set.
       */
      public boolean hasContact() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       * @return The contact.
       */
      public com.scratch.contact.ContactProto.Contact getContact() {
        if (contactBuilder_ == null) {
          return contact_ == null ? com.scratch.contact.ContactProto.Contact.getDefaultInstance() : contact_;
        } else {
          return contactBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public Builder setContact(com.scratch.contact.ContactProto.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contact_ = value;
          onChanged();
        } else {
          contactBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public Builder setContact(
          com.scratch.contact.ContactProto.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          contact_ = builderForValue.build();
          onChanged();
        } else {
          contactBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public Builder mergeContact(com.scratch.contact.ContactProto.Contact value) {
        if (contactBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              contact_ != null &&
              contact_ != com.scratch.contact.ContactProto.Contact.getDefaultInstance()) {
            contact_ =
              com.scratch.contact.ContactProto.Contact.newBuilder(contact_).mergeFrom(value).buildPartial();
          } else {
            contact_ = value;
          }
          onChanged();
        } else {
          contactBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = null;
          onChanged();
        } else {
          contactBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public com.scratch.contact.ContactProto.Contact.Builder getContactBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContactFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      public com.scratch.contact.ContactProto.ContactOrBuilder getContactOrBuilder() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilder();
        } else {
          return contact_ == null ?
              com.scratch.contact.ContactProto.Contact.getDefaultInstance() : contact_;
        }
      }
      /**
       * <code>optional .contact.Contact contact = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.contact.ContactProto.Contact, com.scratch.contact.ContactProto.Contact.Builder, com.scratch.contact.ContactProto.ContactOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.scratch.contact.ContactProto.Contact, com.scratch.contact.ContactProto.Contact.Builder, com.scratch.contact.ContactProto.ContactOrBuilder>(
                  getContact(),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:address_book.AddressBookEntry)
    }

    // @@protoc_insertion_point(class_scope:address_book.AddressBookEntry)
    private static final com.scratch.address_book.AddressBookEntryProto.AddressBookEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scratch.address_book.AddressBookEntryProto.AddressBookEntry();
    }

    public static com.scratch.address_book.AddressBookEntryProto.AddressBookEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AddressBookEntry>
        PARSER = new com.google.protobuf.AbstractParser<AddressBookEntry>() {
      @java.lang.Override
      public AddressBookEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBookEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressBookEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBookEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scratch.address_book.AddressBookEntryProto.AddressBookEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_address_book_AddressBookEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_address_book_AddressBookEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022address_book.proto\022\014address_book\032\014pers" +
      "on.proto\032\rcontact.proto\"U\n\020AddressBookEn" +
      "try\022\036\n\006person\030\001 \001(\0132\016.person.Person\022!\n\007c" +
      "ontact\030\002 \001(\0132\020.contact.ContactB1\n\030com.sc" +
      "ratch.address_bookB\025AddressBookEntryProt" +
      "o"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.scratch.person.PersonProto.getDescriptor(),
          com.scratch.contact.ContactProto.getDescriptor(),
        });
    internal_static_address_book_AddressBookEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_address_book_AddressBookEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_address_book_AddressBookEntry_descriptor,
        new java.lang.String[] { "Person", "Contact", });
    com.scratch.person.PersonProto.getDescriptor();
    com.scratch.contact.ContactProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
