// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.scratch.person;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:person.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 2;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 2;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional .person.Person.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>optional .person.Person.Address address = 3;</code>
     * @return The address.
     */
    com.scratch.person.PersonProto.Person.Address getAddress();
    /**
     * <code>optional .person.Person.Address address = 3;</code>
     */
    com.scratch.person.PersonProto.Person.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code person.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:person.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              email_ = s;
              break;
            }
            case 26: {
              com.scratch.person.PersonProto.Person.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.scratch.person.PersonProto.Person.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scratch.person.PersonProto.internal_static_person_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scratch.person.PersonProto.internal_static_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scratch.person.PersonProto.Person.class, com.scratch.person.PersonProto.Person.Builder.class);
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:person.Person.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional uint32 doorNo = 1;</code>
       * @return Whether the doorNo field is set.
       */
      boolean hasDoorNo();
      /**
       * <code>optional uint32 doorNo = 1;</code>
       * @return The doorNo.
       */
      int getDoorNo();

      /**
       * <code>repeated string street = 2;</code>
       * @return A list containing the street.
       */
      java.util.List<java.lang.String>
          getStreetList();
      /**
       * <code>repeated string street = 2;</code>
       * @return The count of street.
       */
      int getStreetCount();
      /**
       * <code>repeated string street = 2;</code>
       * @param index The index of the element to return.
       * @return The street at the given index.
       */
      java.lang.String getStreet(int index);
      /**
       * <code>repeated string street = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the street at the given index.
       */
      com.google.protobuf.ByteString
          getStreetBytes(int index);

      /**
       * <code>optional string city = 3;</code>
       * @return Whether the city field is set.
       */
      boolean hasCity();
      /**
       * <code>optional string city = 3;</code>
       * @return The city.
       */
      java.lang.String getCity();
      /**
       * <code>optional string city = 3;</code>
       * @return The bytes for city.
       */
      com.google.protobuf.ByteString
          getCityBytes();
    }
    /**
     * Protobuf type {@code person.Person.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:person.Person.Address)
        AddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        street_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        city_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Address();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                doorNo_ = input.readUInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                  street_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                street_.add(s);
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                city_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) != 0)) {
            street_ = street_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scratch.person.PersonProto.internal_static_person_Person_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scratch.person.PersonProto.internal_static_person_Person_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scratch.person.PersonProto.Person.Address.class, com.scratch.person.PersonProto.Person.Address.Builder.class);
      }

      private int bitField0_;
      public static final int DOORNO_FIELD_NUMBER = 1;
      private int doorNo_;
      /**
       * <code>optional uint32 doorNo = 1;</code>
       * @return Whether the doorNo field is set.
       */
      @java.lang.Override
      public boolean hasDoorNo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 doorNo = 1;</code>
       * @return The doorNo.
       */
      @java.lang.Override
      public int getDoorNo() {
        return doorNo_;
      }

      public static final int STREET_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList street_;
      /**
       * <code>repeated string street = 2;</code>
       * @return A list containing the street.
       */
      public com.google.protobuf.ProtocolStringList
          getStreetList() {
        return street_;
      }
      /**
       * <code>repeated string street = 2;</code>
       * @return The count of street.
       */
      public int getStreetCount() {
        return street_.size();
      }
      /**
       * <code>repeated string street = 2;</code>
       * @param index The index of the element to return.
       * @return The street at the given index.
       */
      public java.lang.String getStreet(int index) {
        return street_.get(index);
      }
      /**
       * <code>repeated string street = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the street at the given index.
       */
      public com.google.protobuf.ByteString
          getStreetBytes(int index) {
        return street_.getByteString(index);
      }

      public static final int CITY_FIELD_NUMBER = 3;
      private volatile java.lang.Object city_;
      /**
       * <code>optional string city = 3;</code>
       * @return Whether the city field is set.
       */
      @java.lang.Override
      public boolean hasCity() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string city = 3;</code>
       * @return The city.
       */
      @java.lang.Override
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       * @return The bytes for city.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeUInt32(1, doorNo_);
        }
        for (int i = 0; i < street_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, street_.getRaw(i));
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, doorNo_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < street_.size(); i++) {
            dataSize += computeStringSizeNoTag(street_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getStreetList().size();
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.scratch.person.PersonProto.Person.Address)) {
          return super.equals(obj);
        }
        com.scratch.person.PersonProto.Person.Address other = (com.scratch.person.PersonProto.Person.Address) obj;

        if (hasDoorNo() != other.hasDoorNo()) return false;
        if (hasDoorNo()) {
          if (getDoorNo()
              != other.getDoorNo()) return false;
        }
        if (!getStreetList()
            .equals(other.getStreetList())) return false;
        if (hasCity() != other.hasCity()) return false;
        if (hasCity()) {
          if (!getCity()
              .equals(other.getCity())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDoorNo()) {
          hash = (37 * hash) + DOORNO_FIELD_NUMBER;
          hash = (53 * hash) + getDoorNo();
        }
        if (getStreetCount() > 0) {
          hash = (37 * hash) + STREET_FIELD_NUMBER;
          hash = (53 * hash) + getStreetList().hashCode();
        }
        if (hasCity()) {
          hash = (37 * hash) + CITY_FIELD_NUMBER;
          hash = (53 * hash) + getCity().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.scratch.person.PersonProto.Person.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.scratch.person.PersonProto.Person.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.scratch.person.PersonProto.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.scratch.person.PersonProto.Person.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code person.Person.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:person.Person.Address)
          com.scratch.person.PersonProto.Person.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.scratch.person.PersonProto.internal_static_person_Person_Address_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.scratch.person.PersonProto.internal_static_person_Person_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.scratch.person.PersonProto.Person.Address.class, com.scratch.person.PersonProto.Person.Address.Builder.class);
        }

        // Construct using com.scratch.person.PersonProto.Person.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          doorNo_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          street_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.scratch.person.PersonProto.internal_static_person_Person_Address_descriptor;
        }

        @java.lang.Override
        public com.scratch.person.PersonProto.Person.Address getDefaultInstanceForType() {
          return com.scratch.person.PersonProto.Person.Address.getDefaultInstance();
        }

        @java.lang.Override
        public com.scratch.person.PersonProto.Person.Address build() {
          com.scratch.person.PersonProto.Person.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.scratch.person.PersonProto.Person.Address buildPartial() {
          com.scratch.person.PersonProto.Person.Address result = new com.scratch.person.PersonProto.Person.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.doorNo_ = doorNo_;
            to_bitField0_ |= 0x00000001;
          }
          if (((bitField0_ & 0x00000002) != 0)) {
            street_ = street_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.street_ = street_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.city_ = city_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.scratch.person.PersonProto.Person.Address) {
            return mergeFrom((com.scratch.person.PersonProto.Person.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.scratch.person.PersonProto.Person.Address other) {
          if (other == com.scratch.person.PersonProto.Person.Address.getDefaultInstance()) return this;
          if (other.hasDoorNo()) {
            setDoorNo(other.getDoorNo());
          }
          if (!other.street_.isEmpty()) {
            if (street_.isEmpty()) {
              street_ = other.street_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStreetIsMutable();
              street_.addAll(other.street_);
            }
            onChanged();
          }
          if (other.hasCity()) {
            bitField0_ |= 0x00000004;
            city_ = other.city_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.scratch.person.PersonProto.Person.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.scratch.person.PersonProto.Person.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int doorNo_ ;
        /**
         * <code>optional uint32 doorNo = 1;</code>
         * @return Whether the doorNo field is set.
         */
        @java.lang.Override
        public boolean hasDoorNo() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional uint32 doorNo = 1;</code>
         * @return The doorNo.
         */
        @java.lang.Override
        public int getDoorNo() {
          return doorNo_;
        }
        /**
         * <code>optional uint32 doorNo = 1;</code>
         * @param value The doorNo to set.
         * @return This builder for chaining.
         */
        public Builder setDoorNo(int value) {
          bitField0_ |= 0x00000001;
          doorNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 doorNo = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDoorNo() {
          bitField0_ = (bitField0_ & ~0x00000001);
          doorNo_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList street_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureStreetIsMutable() {
          if (!((bitField0_ & 0x00000002) != 0)) {
            street_ = new com.google.protobuf.LazyStringArrayList(street_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string street = 2;</code>
         * @return A list containing the street.
         */
        public com.google.protobuf.ProtocolStringList
            getStreetList() {
          return street_.getUnmodifiableView();
        }
        /**
         * <code>repeated string street = 2;</code>
         * @return The count of street.
         */
        public int getStreetCount() {
          return street_.size();
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param index The index of the element to return.
         * @return The street at the given index.
         */
        public java.lang.String getStreet(int index) {
          return street_.get(index);
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param index The index of the value to return.
         * @return The bytes of the street at the given index.
         */
        public com.google.protobuf.ByteString
            getStreetBytes(int index) {
          return street_.getByteString(index);
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param index The index to set the value at.
         * @param value The street to set.
         * @return This builder for chaining.
         */
        public Builder setStreet(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureStreetIsMutable();
          street_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param value The street to add.
         * @return This builder for chaining.
         */
        public Builder addStreet(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureStreetIsMutable();
          street_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param values The street to add.
         * @return This builder for chaining.
         */
        public Builder addAllStreet(
            java.lang.Iterable<java.lang.String> values) {
          ensureStreetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, street_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string street = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStreet() {
          street_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string street = 2;</code>
         * @param value The bytes of the street to add.
         * @return This builder for chaining.
         */
        public Builder addStreetBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureStreetIsMutable();
          street_.add(value);
          onChanged();
          return this;
        }

        private java.lang.Object city_ = "";
        /**
         * <code>optional string city = 3;</code>
         * @return Whether the city field is set.
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string city = 3;</code>
         * @return The city.
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            city_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string city = 3;</code>
         * @return The bytes for city.
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string city = 3;</code>
         * @param value The city to set.
         * @return This builder for chaining.
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000004);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 3;</code>
         * @param value The bytes for city to set.
         * @return This builder for chaining.
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:person.Person.Address)
      }

      // @@protoc_insertion_point(class_scope:person.Person.Address)
      private static final com.scratch.person.PersonProto.Person.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.scratch.person.PersonProto.Person.Address();
      }

      public static com.scratch.person.PersonProto.Person.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        @java.lang.Override
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.scratch.person.PersonProto.Person.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string email = 2;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private com.scratch.person.PersonProto.Person.Address address_;
    /**
     * <code>optional .person.Person.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .person.Person.Address address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public com.scratch.person.PersonProto.Person.Address getAddress() {
      return address_ == null ? com.scratch.person.PersonProto.Person.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .person.Person.Address address = 3;</code>
     */
    @java.lang.Override
    public com.scratch.person.PersonProto.Person.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? com.scratch.person.PersonProto.Person.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scratch.person.PersonProto.Person)) {
        return super.equals(obj);
      }
      com.scratch.person.PersonProto.Person other = (com.scratch.person.PersonProto.Person) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scratch.person.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scratch.person.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scratch.person.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scratch.person.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scratch.person.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code person.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:person.Person)
        com.scratch.person.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scratch.person.PersonProto.internal_static_person_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scratch.person.PersonProto.internal_static_person_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scratch.person.PersonProto.Person.class, com.scratch.person.PersonProto.Person.Builder.class);
      }

      // Construct using com.scratch.person.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scratch.person.PersonProto.internal_static_person_Person_descriptor;
      }

      @java.lang.Override
      public com.scratch.person.PersonProto.Person getDefaultInstanceForType() {
        return com.scratch.person.PersonProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.scratch.person.PersonProto.Person build() {
        com.scratch.person.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scratch.person.PersonProto.Person buildPartial() {
        com.scratch.person.PersonProto.Person result = new com.scratch.person.PersonProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (addressBuilder_ == null) {
            result.address_ = address_;
          } else {
            result.address_ = addressBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scratch.person.PersonProto.Person) {
          return mergeFrom((com.scratch.person.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scratch.person.PersonProto.Person other) {
        if (other == com.scratch.person.PersonProto.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scratch.person.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scratch.person.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       * @return Whether the email field is set.
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string email = 2;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      private com.scratch.person.PersonProto.Person.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.person.PersonProto.Person.Address, com.scratch.person.PersonProto.Person.Address.Builder, com.scratch.person.PersonProto.Person.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       * @return The address.
       */
      public com.scratch.person.PersonProto.Person.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.scratch.person.PersonProto.Person.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public Builder setAddress(com.scratch.person.PersonProto.Person.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public Builder setAddress(
          com.scratch.person.PersonProto.Person.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public Builder mergeAddress(com.scratch.person.PersonProto.Person.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              address_ != null &&
              address_ != com.scratch.person.PersonProto.Person.Address.getDefaultInstance()) {
            address_ =
              com.scratch.person.PersonProto.Person.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public com.scratch.person.PersonProto.Person.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      public com.scratch.person.PersonProto.Person.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.scratch.person.PersonProto.Person.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .person.Person.Address address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.scratch.person.PersonProto.Person.Address, com.scratch.person.PersonProto.Person.Address.Builder, com.scratch.person.PersonProto.Person.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.scratch.person.PersonProto.Person.Address, com.scratch.person.PersonProto.Person.Address.Builder, com.scratch.person.PersonProto.Person.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:person.Person)
    }

    // @@protoc_insertion_point(class_scope:person.Person)
    private static final com.scratch.person.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scratch.person.PersonProto.Person();
    }

    public static com.scratch.person.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scratch.person.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\006person\"\323\001\n\006Person\022\021\n\004nam" +
      "e\030\001 \001(\tH\000\210\001\001\022\022\n\005email\030\002 \001(\tH\001\210\001\001\022,\n\007addr" +
      "ess\030\003 \001(\0132\026.person.Person.AddressH\002\210\001\001\032U" +
      "\n\007Address\022\023\n\006doorNo\030\001 \001(\rH\000\210\001\001\022\016\n\006street" +
      "\030\002 \003(\t\022\021\n\004city\030\003 \001(\tH\001\210\001\001B\t\n\007_doorNoB\007\n\005" +
      "_cityB\007\n\005_nameB\010\n\006_emailB\n\n\010_addressB!\n\022" +
      "com.scratch.personB\013PersonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_descriptor,
        new java.lang.String[] { "Name", "Email", "Address", "Name", "Email", "Address", });
    internal_static_person_Person_Address_descriptor =
      internal_static_person_Person_descriptor.getNestedTypes().get(0);
    internal_static_person_Person_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_Address_descriptor,
        new java.lang.String[] { "DoorNo", "Street", "City", "DoorNo", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
